### ISSUE TITLE
Can't open the docs page.

### ISSUE THREAD

**Issue by PhbsSmn** [RobinVercammen/graphql-visug-september#1]
Hi,

I'm not sure how I can access the docs. The index.html doesn't boot the presentation. Is it possible to export it to a pdf format or something else?

**Comment by RobinVercammen** [comment]
Hi, it's using github pages for hosting so you'll be able to find it on https://robinvercammen.github.io/graphql-visug-september/. It is also possible to 'run' the docs locally by doing `npm install` followed by `npm start` in the docs folder. Detailed explanation for exporting to pdf (only works in chrome) can be found at https://github.com/hakimel/reveal.js#pdf-export.
It boils down to this:

1. Go to https://robinvercammen.github.io/graphql-visug-september/?print-pdf
2. Open browser print dialog
3. Tick the enable background images
4. Choose to export to pdf
5. Print
